version: "3.0"

services:

  # PostgreSQL
  postgresql:
    container_name: postgresql
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_DB=acme
      - POSTGRES_USER=postgresql-username
      - POSTGRES_PASSWORD=postgresql-password
    networks:
      - network-postgresql
    ports:
      - 5432:5432

  # Elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.12
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - network-elasticsearch
    ports:
      - 9200:9200

  # Kibana
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.8.12
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - network-elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:

  network-postgresql:
    driver: bridge
  network-elasticsearch:
    driver: bridge
